// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjfiowuectwtvnyfrsgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZmlvd3VlY3R3dHZueWZyc2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NjM0MTUsImV4cCI6MjA3NjAzOTQxNX0.7WFutjOPcSlgPAu-LqpJ-s7lWjjL5HtQ0y6zlz-1s3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});